name: bodymax
description: A fitness tracking and body transformation app

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  dio: ^5.3.3
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/